# Generated by Django 5.0.6 on 2024-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewresults',
            old_name='name',
            new_name='applicant',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='application_id',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='application id'),
        ),
    ]
