# Generated by Django 5.0.6 on 2024-05-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_rename_name_interviewresults_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='work_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Work Experience'),
        ),
    ]
