# Generated by Django 5.0.6 on 2024-05-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_interviewresults_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewresults',
            old_name='InterViewScore',
            new_name='score',
        ),
    ]
