# Generated by Django 5.0.6 on 2024-05-19 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_rename_interviewscore_interviewresults_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresults',
            name='name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruitment.applicant'),
            preserve_default=False,
        ),
    ]
