# Generated by Django 5.0.6 on 2024-05-26 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_applicant_work_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='applicant',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(default='ahmad', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
