# Generated by Django 5.0.6 on 2024-05-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_interviewresults_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresults',
            name='user',
        ),
    ]
