# Generated by Django 5.0.6 on 2024-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='amount',
            new_name='basic_salary',
        ),
        migrations.RenameField(
            model_name='salaryrecord',
            old_name='extra_hours',
            new_name='extra_hours_wages',
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='month',
            field=models.DateField(),
        ),
    ]
