# Generated by Django 5.0.6 on 2024-06-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0002_rename_amount_salaryrecord_basic_salary_and_more'),
        ('labor', '0011_remove_hourlyattendance_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaryRecord',
            new_name='Salary',
        ),
    ]
