# Generated by Django 5.0.6 on 2024-05-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0002_alter_salaryadjustment_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='start_date',
        ),
    ]
