# Generated by Django 5.0.6 on 2024-06-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0003_rename_salaryrecord_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='extra_hours_wages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
