# Generated by Django 5.0.6 on 2024-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0004_alter_salary_extra_hours_wages'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadjustment',
            name='for_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryadjustment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
