# Generated by Django 5.0.6 on 2024-07-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0006_alter_salaryadjustment_amount_and_more'),
        ('labor', '0011_remove_hourlyattendance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='progress_report',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='project',
            name='currentStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('todo', 'Todo'), ('doing', 'Doing'), ('testing', 'Testing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labor.labor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='labor.labor'),
        ),
    ]
