# Generated by Django 5.0.6 on 2024-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0007_rename_end_date_project_deadline_and_more'),
        ('labor', '0011_remove_hourlyattendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('labor', models.ManyToManyField(related_name='departments', to='labor.labor')),
            ],
        ),
    ]
