# Generated by Django 5.0.6 on 2024-07-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0008_departments'),
        ('labor', '0011_remove_hourlyattendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='labor',
            field=models.ManyToManyField(blank=True, null=True, related_name='departments', to='labor.labor'),
        ),
    ]
