# Generated by Django 5.0.6 on 2024-07-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0009_alter_departments_labor'),
        ('labor', '0013_labor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='labor.labor'),
        ),
    ]
