# Generated by Django 5.0.3 on 2024-05-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_id',
            field=models.CharField(default='LAPID-0001', max_length=10, verbose_name='Application ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reviewercomment',
            name='commentator',
        ),
        migrations.AddField(
            model_name='reviewercomment',
            name='commentator',
            field=models.ManyToManyField(blank=True, to='labor.labor'),
        ),
    ]
