# Generated by Django 5.0.6 on 2024-06-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_id', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Labor ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('cnic', models.CharField(max_length=13, unique=True, verbose_name='CNIC')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('post', models.CharField(choices=[('labor', 'Labor'), ('supervisor', 'Supervisor'), ('ceo', 'CEO')], default='Labor', max_length=10, verbose_name='Post')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Pay')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_hire', models.DateField(auto_now_add=True, verbose_name='Date of Hire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labors',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='labor.labor')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'unique_together': {('labor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.attendance')),
            ],
            options={
                'verbose_name_plural': 'Hourly Attendance',
                'unique_together': {('check_in', 'attendance')},
            },
        ),
    ]
