# Generated by Django 5.0.6 on 2024-05-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_id', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Labor ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('cnic', models.CharField(max_length=13, unique=True, verbose_name='CNIC')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('post', models.CharField(choices=[('labor', 'Labor'), ('supervisor', 'Supervisor')], max_length=10, verbose_name='Post')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Pay')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_hire', models.DateField(verbose_name='Date of Hire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labors',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
