# Generated by Django 5.0.6 on 2024-05-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='post',
            field=models.CharField(choices=[('labor', 'Labor'), ('supervisor', 'Supervisor'), ('ceo', 'CEO')], max_length=10, verbose_name='Post'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='labor.labor')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='HourlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], max_length=10)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.attendance')),
            ],
            options={
                'verbose_name_plural': 'Hourly Attendance',
            },
        ),
    ]
