# Generated by Django 5.0.6 on 2024-05-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_alter_labor_post_attendance_hourlyattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('labor', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hourlyattendance',
            unique_together={('check_in', 'attendance')},
        ),
    ]
