# Generated by Django 5.0.6 on 2024-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0003_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='date_of_hire',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Hire'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='post',
            field=models.CharField(choices=[('labor', 'Labor'), ('supervisor', 'Supervisor'), ('ceo', 'CEO')], default='Labor', max_length=10, verbose_name='Post'),
        ),
    ]
