# Generated by Django 5.0.6 on 2024-06-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(default=None),
        ),
    ]
