# Generated by Django 5.0.6 on 2024-06-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_alter_hourlyattendance_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyattendance',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyattendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
