# Generated by Django 5.0.6 on 2024-07-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0009_alter_departments_labor'),
        ('labor', '0011_remove_hourlyattendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labour_department', to='ceo.departments'),
            preserve_default=False,
        ),
    ]
