# Generated by Django 5.0.6 on 2024-07-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0012_labor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='image',
            field=models.ImageField(default='sldk', upload_to='LabourProfile'),
            preserve_default=False,
        ),
    ]
