# Generated by Django 5.0.6 on 2024-07-07 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo', '0011_designations'),
        ('labor', '0013_labor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ceo.designations'),
            preserve_default=False,
        ),
    ]
